# Generated by Django 3.1.2 on 2020-10-27 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201027_0801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='correo',
            new_name='animo',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='rfc',
            new_name='mensaje',
        ),
    ]
